site_name: Genomics Platform Docs
pages:
- 'Home': 'index.md'
- 'Documentation':
  - 'HPC Access': 'hpc-access/index.md'
  - 'HPC Archiving': 'hpc-archive/index.md'
  - 'HPC Updates': 'hpc-update/index.md'
- 'Support files': 'materials/index.md'
extra_templates: [
]
extra_javascript: [
  'includes/remark-latest.min.js', 
  'includes/media/delayed-jquery.js', 
  'includes/media/mdx_showable.js'
]
extra_css: [
  'includes/media/mdx_showable.css', 
  'includes/media/mdx_showable_user.css', 
#  'includes/media/plain-slides.css', 
  'includes/media/tute.css'
]
markdown_extensions: [
  'markdown_include.include',
  'showable',
  'markdown.extensions.fenced_code',
#  'environment',
]
